package org.semanticscience.hyquespinservlet.server;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.semanticscience.hyquespinservlet.lib.Hypothesis;
import org.semanticscience.hyquespinservlet.lib.HypothesisParser;
import org.topbraid.spin.inference.SPINInferences;
import org.topbraid.spin.system.SPINModuleRegistry;
import org.topbraid.spin.util.SystemTriples;

import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;

public class HyQueSPINExecutor extends HttpServlet {

	static String inputParameter = "inputHypothesis";
	static String inputFileParameter = "inputHypothesisFile";
	static String inputFormatParameter = "inputFormat";
	static String outputFormatParameter = "outputFormat";
	static String jsTreeParameter = "jstree";
	static String rulesParameter = "spinFile";

	// create OntModel
	static OntModel hyqueSPINModel = ModelFactory
			.createOntologyModel(OntModelSpec.OWL_MEM);

	static OntModel spinOnlyModel = ModelFactory
			.createOntologyModel(OntModelSpec.OWL_MEM);

	public enum Format {
		JSON, RDF
	}

	@Override
	public void init() {
		// Initialize system functions and templates
		SPINModuleRegistry.get().init();

		// add system triples
		hyqueSPINModel.add(SystemTriples.getVocabularyModel());

	}

	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException {

		PrintWriter out = null;
		String input = null;

		boolean jstree = false;

		try {
			out = resp.getWriter();

			Format format = Format.RDF;
			resp.setContentType("text/xml");

			String rules = req.getParameter(rulesParameter);

			//read SPIN rules into hyqueSPINModel and spinOnlyModel
			hyqueSPINModel.read(rules);
			spinOnlyModel.read(rules);

			if (req.getParameter(inputFileParameter) != null
					&& req.getParameter(inputParameter) != null) {
				out.print("Provide EITHER the URL of a file containing the hypothesis RDF using the inputHypothesisFile parameter OR a string of the hypothesis RDF using the inputHypothesis parameter");
			} else if (req.getParameter(inputFileParameter) != null) {
				String fileURL = req.getParameter(inputFileParameter);
				URL inputURL = new URL(fileURL);
				URLConnection connection = inputURL.openConnection();
				BufferedReader in = new BufferedReader(new InputStreamReader(
						connection.getInputStream()));

				StringBuilder response = new StringBuilder();
				String inputLine;

				while ((inputLine = in.readLine()) != null) {
					response.append(inputLine);
				}
				in.close();

				input = response.toString();
			} else if (req.getParameter(inputParameter) != null) {
				input = req.getParameter(inputParameter);
			}

			if (req.getParameter(outputFormatParameter) != null
					&& req.getParameter(outputFormatParameter).toLowerCase()
							.equals("json")) {
				format = Format.JSON;
				resp.setContentType("application/json");
			}

			if (req.getParameter(jsTreeParameter) != null
					&& req.getParameter(jsTreeParameter).toLowerCase()
							.equals("true")) {
				jstree = true;
			}

			Model inputModel = null;

			if (req.getParameter(inputFormatParameter) != null
					&& req.getParameter(inputFormatParameter).toLowerCase()
							.equals("json")) {
				Hypothesis hyp = new Hypothesis(input);
				inputModel = hyp.makeHypothesisModel();
			} else if (req.getParameter(inputFormatParameter) != null
					&& req.getParameter(inputFormatParameter).toLowerCase()
							.equals("rdf")) {
				inputModel = ModelFactory.createDefaultModel();
				InputStream is = new ByteArrayInputStream(input.getBytes());
				inputModel.read(is, null);
				is.close();
			}

			// add input model to SPIN model
			hyqueSPINModel.addSubModel(inputModel);

			// create output model to contain inferred statements
			Model evaluationModel = ModelFactory.createDefaultModel();

			// add output model to SPIN model
			hyqueSPINModel.addSubModel(evaluationModel);

			// register locally defined functions
			SPINModuleRegistry.get().registerAll(hyqueSPINModel, null);

			// run SPIN inferences
			SPINInferences.run(hyqueSPINModel, evaluationModel, null, null,
					false, null);

			// add input model and SPIN rules to evaluation model, so all data
			// (provided by user and generated by HyQue) is sent back to user
			evaluationModel.add(inputModel);

			makeOutput(out, format, evaluationModel, jstree);

			// remove input and evaluation models from hyqueSPINModel
			hyqueSPINModel.removeSubModel(inputModel);
			hyqueSPINModel.removeSubModel(evaluationModel);

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				out.close();
			} catch (NullPointerException e) {
				e.printStackTrace();
			}
		}
	}

	void makeOutput(PrintWriter out, Format format, Model evaluation,
			boolean jstree) {
		if (format == Format.JSON && jstree == true) {
			out.println(makeJsTreeOutput(evaluation));
		} else if (format == Format.JSON && jstree == false) {
			out.println(makeJSONOutput(evaluation));
		} else {
			out.println(makeRDFOutput(out, evaluation));
		}
	}

	String makeJSONOutput(Model model) {
		String output = HypothesisParser.getJSONString(model, spinOnlyModel);
		return output;
	}

	String makeJsTreeOutput(Model model) {
		String output = HypothesisParser.getJstreeJSON(model, spinOnlyModel);
		return output;
	}

	String makeRDFOutput(PrintWriter out, Model model) {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		model.write(output, "RDF/XML");
		String results = output.toString();
		try {
			output.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return results;
	}
}
